### ISSUE TITLE
Issues with angular 4

### ISSUE THREAD

**Issue by kuncevic** [ngrx/effects#139]
I was running version `2.0.0` fine but with CLI `ng build --prod`
```
ERROR in c:/Projects/work/MyXProj/Source/src/$$_gendir/node_modules/@ngrx/effects/src/effects.module.ngfactory.ts (1,1): Argument of type 'Store<any>' is not assignable to parameter of type 'Observer<Actions>'.
  Types of property 'next' are incompatible.
    Type '(action: Action) => void' is not assignable to type '(value: Actions) => void'.
      Types of parameters 'action' and 'value' are incompatible.
        Type 'Actions' is not assignable to type 'Action'.
          Property 'type' is missing in type 'Actions'.
```
Then I upgraded to `2.0.2` and got runtime error:

```
Unhandled Promise rejection: Cannot convert undefined or null to object ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at combineReducers (vendor.bundle.js:91447)
    at _initialReducerFactory (vendor.bundle.js:153556)
    at AppModuleInjector.get (ng:///AppModule/module.ngfactory.js:342)
    at AppModuleInjector.getInternal (ng:///AppModule/module.ngfactory.js:856)
    at AppModuleInjector.NgModuleInjector.get (vendor.bundle.js:8385)
    at _createReducerIfExtension (vendor.bundle.js:153175)
    at AppModuleInjector.createInternal (ng:///AppModule/module.ngfactory.js:608)
    at AppModuleInjector.NgModuleInjector.create (vendor.bundle.js:8366)
    at NgModuleFactory.create (vendor.bundle.js:8339)
    at vendor.bundle.js:9577
    at ZoneDelegate.webpackJsonp.1187.ZoneDelegate.invoke (polyfills.bundle.js:967)
    at Object.onInvoke (vendor.bundle.js:8954)
    at ZoneDelegate.webpackJsonp.1187.ZoneDelegate.invoke (polyfills.bundle.js:966)
    at Zone.webpackJsonp.1187.Zone.run (polyfills.bundle.js:727) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at combineReducers (http://localhost:4201/vendor.bundle.js:91447:30)
    at _initialReducerFactory (http://localhost:4201/vendor.bundle.js:153556:98)
    at AppModuleInjector.get (ng:///AppModule/module.ngfactory.js:342:107)
    at AppModuleInjector.getInternal (ng:///AppModule/module.ngfactory.js:856:71)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4201/vendor.bundle.js:8385:44)
    at _createReducerIfExtension (http://localhost:4201/vendor.bundle.js:153175:32)
    at AppModuleInjector.createInternal (ng:///AppModule/module.ngfactory.js:608:22)
    at AppModuleInjector.NgModuleInjector.create (http://localhost:4201/vendor.bundle.js:8366:76)
    at NgModuleFactory.create (http://localhost:4201/vendor.bundle.js:8339:18)
    at http://localhost:4201/vendor.bundle.js:9577:61
    at ZoneDelegate.webpackJsonp.1187.ZoneDelegate.invoke (http://localhost:4201/polyfills.bundle.js:967:26)
    at Object.onInvoke (http://localhost:4201/vendor.bundle.js:8954:37)
    at ZoneDelegate.webpackJsonp.1187.ZoneDelegate.invoke (http://localhost:4201/polyfills.bundle.js:966:32)
    at Zone.webpackJsonp.1187.Zone.run (http://localhost:4201/polyfills.bundle.js:727:43)
```
Then run `ng build --prod` - all good.

So currently rolled back to `2.0.0` without option to run  `--prod` builds

**Comment by robertohuertasm** [comment]
Can you get a simple project reproducing the issue?

**Comment by kuncevic** [comment]
```
```

**Comment by robertohuertasm** [comment]
Thanks, but I was thinking more of a project. Anyway, the `aot` error suggests that you have an error in some function and instead of using `Action` (from store) as a type annotation you're using `Actions` (from ngrx). Review your code for functions with an `Actions` parameter.

**Comment by kuncevic** [comment]
OK just revived the code and checked the latest https://github.com/ngrx/example-app
First thing is just got rid of `ActionTypes` and `type` helper:
```
export const ActionTypes = {
  AUTH:           type('User logged in')
  ...
};
```
to 
```
export const AUTH = 'User logged in';
...
```
Second thing was missing the `readonly` on `type` in my `Actions` should be:
```
export class AuthAction implements Action {
  readonly type = AUTH;

  constructor(public payload: AuthDetails) {}
}
```

Now all good.

**Comment by kuncevic** [comment]
So If I target the latest version I got runtime error with effects interfering with the zones. 
I comment my effects to run, then all good. Trying to play with the zones versions now.

**Comment by kuncevic** [comment]
With the version 2.0.0 I still have that issue as `Type 'Actions' is not assignable to type 'Action'.`
But with `2.0.3` it seams to be OK now. No runtime `zone.js` errors any more and i can do `--prod`.

**Comment by kuncevic** [comment]
Just was trying to reproduce an error by creating the new project and realized that it is just works.
So what I done, I just make sure that I have all the same deps:
Before:
```
    "@ngrx/core": "1.2.0",
    "@ngrx/effects": "2.0.3",
    "@ngrx/router-store": "1.2.5",
    "@ngrx/store": "2.2.2",
    "@ngrx/store-devtools": "3.2.2",
    "ngrx-store-freeze": "0.1.6",
    "reselect": "2.5.4",
```
After:
```
    "@ngrx/core": "1.2.0",
    "@ngrx/effects": "2.0.3",
    "@ngrx/router-store": "^1.2.6",
    "@ngrx/store": "2.2.2",
    "@ngrx/store-devtools": "^3.2.4",
    "reselect": "^3.0.0",
```
Then after reinstalling `node_modules` all just works on my project.
I am not closing the issue for now, will keep an eye on it for some time.
