### ISSUE TITLE
When Testing: No provider for toPayload!

### ISSUE THREAD

**Issue by Barryrowe** [ngrx/effects#145]
I'm running into an issue where the EffectsTestingModule doesn't seem to be properly providing the Actions service.

We have an effect that is really doing nothing right now so should be a simple test:
```
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/skip';
import 'rxjs/add/operator/takeUntil';
import { Injectable } from '@angular/core';
import { Effect, Actions, toPayload } from '@ngrx/effects';
import { Action } from '@ngrx/store';
import { Observable } from 'rxjs/Observable';
import { empty } from 'rxjs/observable/empty';

import * as courseActions from '../actions/course.actions';

@Injectable()
export class CourseEffects {

  @Effect()
  search$: Observable<Action> = this.actions$
    .ofType(courseActions.FILL)
    .debounceTime(300)
    .map(toPayload)
    .switchMap(query => {
      console.log('Effect should be firing when the FILL action is dispatched. Effect is firing');
      return empty<Action>();
    });

  constructor(private actions$: Actions) { }
}
```

Our test spec:
```
import { TestBed, inject } from '@angular/core/testing';
import { Actions } from '@ngrx/effects';
import { Observable } from 'rxjs/Observable';
import { EffectsTestingModule, EffectsRunner } from '@ngrx/effects/testing';
import * as courseActions from '../actions/course.actions';
import { CourseEffects }  from '../effects/course.effects';

describe('The Course Effects', () => {
  let runner: EffectsRunner;
  let courseEffects: CourseEffects;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        EffectsTestingModule
      ],
      providers: [
        CourseEffects
      ]
    });
    inject([EffectsRunner, CourseEffects], (_runner, _courseEffects) => {
      runner = _runner;
      courseEffects = _courseEffects;
    })();
  });

  it('should fire search effect when fill action is dispatched and complete action', 
        (done) => {

    runner.queue({ type: courseActions.FILL });

    courseEffects.search$.subscribe(result => {
        expect(result.type).toEqual(courseActions.FILL);
        done();
    });
  });

});
```

This fails with the classic:
> Error: Can't resolve all parameters for CourseEffects: (?).​​
      at ​src/effects/course.effects.spec.ts:21:4​

The only dependency of CourseEffects is ```Actions```, which should be provided by the EffectsTestingModule

So I tried just injecting the Actions service, modifying the test like this:

```
 beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        EffectsTestingModule
      ],
      providers: [
        //CourseEffects
      ]
    });
    inject([EffectsRunner, Actions], (_runner, _actions) => {
      runner = _runner;
      //courseEffects = _courseEffects;
    })();
  });
```

This results in an injection error for the Actions service:

>​​Error: No provider for toPayload!​​
      at ​src/effects/course.effects.spec.ts:21:4

**Comment by Barryrowe** [comment]
This turned out to be an issue with how our tests were being bundled for phantomJS via Wallaby.  

https://github.com/wallabyjs/public/issues/839#issuecomment-278485630
