### ISSUE TITLE
Error: Cannot resolve all parameters for 'StateUpdates'(?, ?) after upgrade to v1.1.0

### ISSUE THREAD

**Issue by karlhaas** [ngrx/effects#29]
After upgrading to v1.1.0 we get the following error:

```
localhost/:140 Error: Error: Cannot resolve all parameters for 'StateUpdates'(?, ?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'StateUpdates' is decorated with Injectable.
	    at NoAnnotationError.BaseException [as constructor] (http://localhost:5555/node_modules/@angular/core/src/facade/exceptions.js:27:23)
	    at new NoAnnotationError (http://localhost:5555/node_modules/@angular/core/src/di/reflective_exceptions.js:225:16)
	    at _dependenciesFor (http://localhost:5555/node_modules/@angular/core/src/di/reflective_provider.js:190:15)
	    at resolveReflectiveFactory (http://localhost:5555/node_modules/@angular/core/src/di/reflective_provider.js:80:24)
	    at resolveReflectiveProvider (http://localhost:5555/node_modules/@angular/core/src/di/reflective_provider.js:104:97)
	    at Array.map (native)
	    at Object.resolveReflectiveProviders (http://localhost:5555/node_modules/@angular/core/src/di/reflective_provider.js:112:31)
	    at Function.ReflectiveInjector.resolve (http://localhost:5555/node_modules/@angular/core/src/di/reflective_injector.js:366:38)
	    at Function.ReflectiveInjector.resolveAndCreate (http://localhost:5555/node_modules/@angular/core/src/di/reflective_injector.js:396:62)
	    at Object.bootstrap (http://localhost:5555/node_modules/@angular/platform-browser-dynamic/index.js:114:49)
```
Downgrading to v1.0.1 works.

**Comment by MikeRyan52** [comment]
Fixed in v1.1.1
