### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by cartant** [ngrx/effects#75]
I've attempted to build the project, as I'd like put some effort into fixing #53. However, I'm receiving the following error:

    > @ngrx/effects@2.0.0 build:js /Users/nicholas/git/github/ngrx/effects
    > ngc -p tsconfig.dist.json

    /Users/nicholas/git/github/ngrx/effects/node_modules/@angular/compiler-cli/src/private_import_compiler.js:10
    exports.AssetUrl = compiler_1.__compiler_private__.AssetUrl;
                                                      ^

    TypeError: Cannot read property 'AssetUrl' of undefined
        at Object.<anonymous> (/Users/nicholas/git/github/ngrx/effects/node_modules/@angular/compiler-cli/src/private_import_compiler.js:10:51)
        at Module._compile (module.js:573:32)
        at Object.Module._extensions..js (module.js:582:10)
        at Module.load (module.js:490:32)
        at tryModuleLoad (module.js:449:12)
        at Function.Module._load (module.js:441:3)
        at Module.require (module.js:500:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/nicholas/git/github/ngrx/effects/node_modules/@angular/compiler-cli/src/reflector_host.js:13:33)
        at Module._compile (module.js:573:32)

I don't particularly want to go down a rabbit hole, investigating this. Any suggestions as to what needs to be done? I've noticed that the CI builds appear to be failing, too - although, much earlier in the build process.

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
