### ISSUE TITLE
When testing: "Error: No provider for EffectsRunner!"

### ISSUE THREAD

**Issue by chapati23** [ngrx/effects#88]
I'm kind of embarrassed to open an issue for something basic like DI but, for the life of me, I can't get it to run. I have a standard angular-cli app with versions:
- angular@2.3.1
- ngrx/effects@2.0.0
- karma@1.2.0

I've followed the testing doc to the letter, this is my super-simplified test:
```typescript
import { TestBed, inject } from '@angular/core/testing'
import { EffectsTestingModule, EffectsRunner } from '@ngrx/effects/testing'

describe('My Effect', () => {
  beforeEach(() => TestBed.configureTestingModule({
    imports: [ EffectsTestingModule ]
  }))
})

let runner: EffectsRunner

beforeEach(inject([EffectsRunner], (_runner) => {
  runner = _runner
}))

it('should just work', () => {
  expect(true).toBe(true)
})
```

This is the DI error in the console:

```bash
	Error: No provider for EffectsRunner!
	Error: DI Error
	    at NoProviderError.BaseError [as constructor] (webpack:///~/@angular/core/src/facade/errors.js:31:0 <- src/test.ts:5782:27) [ProxyZone]
	    at NoProviderError.AbstractProviderError [as constructor] (webpack:///~/@angular/core/src/di/reflective_errors.js:53:0 <- src/test.ts:45193:16) [ProxyZone]
	    at new NoProviderError (webpack:///~/@angular/core/src/di/reflective_errors.js:102:0 <- src/test.ts:45242:16) [ProxyZone]
	    at ReflectiveInjector_._throwOrNull (webpack:///~/@angular/core/src/di/reflective_injector.js:994:0 <- src/test.ts:64085:19) [ProxyZone]
	    at ReflectiveInjector_._getByKeyDefault (webpack:///~/@angular/core/src/di/reflective_injector.js:1031:0 <- src/test.ts:64122:25) [ProxyZone]
	    at ReflectiveInjector_._getByKey (webpack:///~/@angular/core/src/di/reflective_injector.js:981:0 <- src/test.ts:64072:25) [ProxyZone]
	    at ReflectiveInjector_.get (webpack:///~/@angular/core/src/di/reflective_injector.js:743:0 <- src/test.ts:63834:21) [ProxyZone]
	    at TestBed.get (webpack:///~/@angular/core/bundles/core-testing.umd.js:818:0 <- src/test.ts:18741:67) [ProxyZone]
	    at webpack:///~/@angular/core/bundles/core-testing.umd.js:823:50 <- src/test.ts:18746:65 [ProxyZone]
	    at Array.map (native) [ProxyZone]
	    at TestBed.execute (webpack:///~/@angular/core/bundles/core-testing.umd.js:823:0 <- src/test.ts:18746:33) [ProxyZone]
	    at Object.<anonymous> (webpack:///~/@angular/core/bundles/core-testing.umd.js:911:32 <- src/test.ts:18834:49) [ProxyZone]
	    at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- src/test.ts:52711:39) [ProxyZone]
```

What am I missing? Do I need to register the EffectsRunner somewhere else as well maybe?

**Comment by egemenhalici1** [comment]
+1

**Comment by glendaviesnz** [comment]
I think you just need to add your effects provider as the subject of the test, eg.

```
import { TestBed, inject } from '@angular/core/testing';
import { EffectsTestingModule, EffectsRunner } from '@ngrx/effects/testing';

import { AuthEffects } from './auth.effects';

describe('AuthEffects', () => {
    let subject: AuthEffects;
    let runner: EffectsRunner;

    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [
                EffectsTestingModule
            ],
            providers: [AuthEffects]
        });
    });

    beforeEach(inject([AuthEffects, EffectsRunner], 
    (authEffects: AuthEffects, effectsRunner: EffectsRunner) => {
        subject = AuthEffects;
        runner = effectsRunner;
    }));
})
```
But replace AuthEffects with whichever @effects provider is the subject of your current test

**Comment by glendaviesnz** [comment]
Yesterday I had the same error, and it appeared to go away when I add the test subject to the spec, eg. injected in provider that was using @Effect - but, it turns out that the thing that fixed it was including everything in the same describe() section in which you define the testbed module, eg. instead of what you have above try something like
```
import { TestBed, inject } from '@angular/core/testing';
import { EffectsTestingModule, EffectsRunner } from '@ngrx/effects/testing';

describe('Effects stuff...', () => {
    let runner: EffectsRunner;
    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [
                EffectsTestingModule
            ]
        });
    });

    beforeEach(inject([ EffectsRunner],
        ( effectsRunner: EffectsRunner) => {
            runner = effectsRunner;
        }));

    it('should work', () => {
         expect(true).toBe(true);
    });
});
```

**Comment by wisonye** [comment]
@chapati23 @glendaviesnz 

Finally I make it works, actually I think should let everybody know that, as this issue took me a long time to solve it and has NO ANY LUCK by google it !!! :)

[And you won't success to pass `npm test` just by following this guide : https://github.com/ngrx/effects/blob/master/docs/testing.md](https://github.com/ngrx/effects/blob/master/docs/testing.md)


Here is my solution:

***

1. Make sure run **`npm install --save zone.js@0.7.4`** to upgrade the **zone.js**, this can fix the error below:

_`TypeError: Cannot set property 'stack' of undefined at NoProviderError.set [as stack] (node_modules/@angular/core/bundles/core.umd.js:1212:65)`_

***

2. Please have a look my `todolist.effect.spec.ts` file :

```javascript
import { inject, TestBed } from '@angular/core/testing';

import { StoreModule, Action } from '@ngrx/store';
import { EffectsTestingModule, EffectsRunner } from '@ngrx/effects/testing';

import { ToDoListStateActions, todolistReducer } from '../state/index';
import { ToDoListService } from '../services/index';
import { ToDoListEffect } from './index';


/**
 * Manually import all operators which used in testing effect and testing service, to fix the error below:
 * 
 * this.actions$.ofType(...).xxxx is not a function 
 */
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/switchMap';


/**
 * 
 * 
 * @export
 */
export function main() {

    describe('ToDoListEffect Test', () => {

        let runner: EffectsRunner;
        let testEffect: ToDoListEffect;

        /** Import everything we need before each test **/
        beforeEach(() => {
            TestBed.configureTestingModule({

                imports: [
                    // Fix the "Error: No provider for Store!", as usually all "injected service" instances
                    // also inject the "Store" instance in it's construtor !!!
                    StoreModule.provideStore(todolistReducer),

                    EffectsTestingModule
                ],
                providers: [
                    ToDoListService,
                    ToDoListEffect
                ]
            });
        });


        /** Inject everything we need before each test **/
        beforeEach(inject([EffectsRunner, ToDoListEffect], (_runner: EffectsRunner, _testEffect: ToDoListEffect) => {
            runner = _runner;
            testEffect = _testEffect;

            // console.log(`runner: `, runner);
            // console.log(`testEffect: `, testEffect);
        }));



        /**  */
        it('should return a ITEMS_LOADED action after INIT action', () => {
                // console.log(`runner: `, runner);

                // Dispatch INIT action to store
                runner.queue(ToDoListStateActions.init());

                // Subscribe specified "action$" from testing Effect instance
                testEffect.loadItems$.subscribe((resultAction: Action) => {
                    console.log(`resultAction`, resultAction);

                    // After effect logic run, store should have the result action
                    expect(resultAction.type).toEqual(ToDoListStateActions.ITEMS_LOADED);
                });
            }
        );

    });

}
```

***

Finally, you will get this happen ending :)

<img width="890" alt="effecttest_passed" src="https://cloud.githubusercontent.com/assets/3477321/22136881/7388d142-df3c-11e6-9d89-988812f1e91d.png">

**Comment by chapati23** [comment]
thanks so much @wisonye for that detailed solution :)

/offtopic bikeshedding part: coming from an angular1 background and having spent a year almost exclusively with react now i have to admit that testing in angular2 is way, way, way too complex and boilerplate-heavy. i don't wanna compare apples and oranges but the test-code for a redux-saga in react feels _so_ much simpler to me…

**Comment by robwormald** [comment]
New testing APIs are in v4, check them out. Feedback welcome - if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
